[package]
name = "poker_rooms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.17.3"

[[bin]]
name = "poker_rooms"
path = "src/main.rs"