version: "3.9"
services:
  poker_rooms:
    container_name: poker_rooms
    # image: ghcr.io/derrick56007/poker-rooms-server:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8089:8088
    command: poker_rooms